### ISSUE TITLE
canosl

### ISSUE THREAD

**Issue by asfDRT** [Lucky-dummy/Game-Virus-Wars#1]
hi bro, how to make this game for the console?

**Comment by Lucky-dummy** [comment]
I think you can display the field as combinations of ascii characters. It will be necessary to make changes in the classes window and game. After each move, you will need to draw the previous field and wait for the coordinates to be entered into the console. But it is much easier to start from scratch by looking at the algorithms in the "game", "field" and "enemy_ai" classes.
